### ISSUE TITLE
Implement support for NamedMap.isReady()

### ISSUE THREAD

**Issue by rlubke** [oracle/coherence-go-client#27]
14.1.1.2206.5 includes an update to the `NamedMap` called `isReady()` returning a boolean.  

If the client is connecting to an older proxy and `isReady()` is called on the client, it should raise an appropriate error stating the operation isn't supported by the current proxy.  Either upgrade the proxy or connect to a proxy that supports this operation.

**Comment by tmiddlet2666** [comment]
Fixed in https://github.com/oracle/coherence-go-client/pull/45
